Update canvas2d.js
fixed the firefox error if radius*2 < 1.0

error message is:

InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable